import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { GeistMono } from 'geist/font/mono';
import { type Metadata } from "next";
import { cn } from "~/lib/utils";
import { TRPCReactProvider } from "~/trpc/react";
import { Navbar } from "./_components/navbar";
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={cn(
          GeistSans.variable,
          GeistMono.variable,
          'bg-white font-sans dark:bg-neutral-950'
        )}
      >
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Navbar />
        <Toaster />
      </body>
    </html>
  );
}
